require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

#Style/StringLiterals:
#  Enabled: true
#  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "*spec"
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "*spec"
    - "**/*_spec.rb"



